# -*- coding: utf-8 -*-
"""colabcheck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtrbQwtevF2bUkdJ3VM3SfMGVzU1H4WJ
"""

from google.colab import drive
drive.mount('/content/drive')

print("✅ Google Drive mounted successfully!")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import warnings
warnings.filterwarnings('ignore')

print("✅ All libraries imported successfully!")
print("\nLibrary versions:")
print(f"  pandas: {pd.__version__}")
print(f"  numpy: {np.__version__}")
print(f"  scikit-learn: {sklearn.__version__}")

from google.colab import files

print("📁 Select your CSV files to upload...")
uploaded = files.upload()

print("\n✅ Files uploaded:")
for filename in uploaded.keys():
    print(f" - {filename}")

child_df = pd.read_csv('Child_dataset.csv', index_col=0)
adult_df = pd.read_csv('adult_dataset.csv')
old_df = pd.read_csv('old_people_dataset.csv')
print("✅ Datasets loaded successfully!\n")

print("=" * 60)
print("CHILD DATASET")
print("=" * 60)
print(f"Shape: {child_df.shape}")
print(f"Columns: {child_df.columns.tolist()}")
print("\nFirst few rows:")
print(child_df.head())
print(f"\nData types:\n{child_df.dtypes}")
print(f"\nMissing values:\n{child_df.isnull().sum()}")

print("\n" + "=" * 60)
print("ADULT DATASET")
print("=" * 60)
print(f"Shape: {adult_df.shape}")
print(f"Columns: {adult_df.columns.tolist()}")
print("\nFirst few rows:")
print(adult_df.head())

print("\n" + "=" * 60)
print("OLD PEOPLE DATASET")
print("=" * 60)
print(f"Shape: {old_df.shape}")
print(f"Columns: {old_df.columns.tolist()}")
print("\nFirst few rows:")
print(old_df.head())

print("🧹 STEP 1: Removing Duplicates\n")

print(f"Child Dataset - Duplicates: {child_df.duplicated().sum()}")
child_df = child_df.drop_duplicates()

print(f"Adult Dataset - Duplicates: {adult_df.duplicated().sum()}")
adult_df = adult_df.drop_duplicates()

print(f"Old People Dataset - Duplicates: {old_df.duplicated().sum()}")
old_df = old_df.drop_duplicates()

print("\n✅ Duplicates removed!")
print(f"Child: {child_df.shape}")
print(f"Adult: {adult_df.shape}")
print(f"Old: {old_df.shape}")

print("🧹 STEP 2: Handling Missing Values\n")

# CHILD DATASET
if child_df.isnull().sum().sum() > 0:
    print("Child Dataset - Missing values found:")
    print(child_df.isnull().sum())
    child_df = child_df.dropna(subset=['ppvt'])  # Drop if IQ missing
    numeric_cols = child_df.select_dtypes(include=['number']).columns
    for col in numeric_cols:
        child_df[col].fillna(child_df[col].median(), inplace=True)
    print("✓ Filled with median")
else:
    print("✓ Child Dataset - No missing values")

# ADULT DATASET
if adult_df.isnull().sum().sum() > 0:
    print("\nAdult Dataset - Missing values found:")
    numeric_cols = adult_df.select_dtypes(include=['number']).columns
    for col in numeric_cols:
        adult_df[col].fillna(adult_df[col].median(), inplace=True)
    categorical_cols = adult_df.select_dtypes(include=['object']).columns
    for col in categorical_cols:
        adult_df[col].fillna(adult_df[col].mode()[0], inplace=True)
    print("✓ Filled with median/mode")
else:
    print("✓ Adult Dataset - No missing values")

# OLD PEOPLE DATASET
if old_df.isnull().sum().sum() > 0:
    print("\nOld People Dataset - Missing values found:")
    numeric_cols = old_df.select_dtypes(include=['number']).columns
    for col in numeric_cols:
        old_df[col].fillna(old_df[col].median(), inplace=True)
    categorical_cols = old_df.select_dtypes(include=['object']).columns
    for col in categorical_cols:
        old_df[col].fillna(old_df[col].mode()[0], inplace=True)
    print("✓ Filled with median/mode")
else:
    print("✓ Old People Dataset - No missing values")

print("\n✅ Missing value handling complete!")

print("📊 STEP 3: Adding Age Column to Child Dataset\n")

np.random.seed(42)
n_samples = len(child_df)

np.random.seed(42)

n = len(child_df)

# Calculate exact sizes
n1 = int(0.10 * n)
n2 = int(0.20 * n)
n3 = int(0.35 * n)
n4 = n - (n1 + n2 + n3)   # ✅ FIX HERE

ages_months = np.concatenate([
    np.random.uniform(0, 3, n1),
    np.random.uniform(3, 12, n2),
    np.random.uniform(12, 24, n3),
    np.random.uniform(24, 36, n4)
])

np.random.shuffle(ages_months)

child_df["age_months"] = ages_months
child_df["age_years"] = child_df["age_months"] / 12

print("✅ Age columns added!")
print(f"\nAge Distribution:")
print(f"  Min: {child_df['age_months'].min():.2f} months")
print(f"  Max: {child_df['age_months'].max():.2f} months")
print(f"  Mean: {child_df['age_months'].mean():.2f} months")
print(f"  Median: {child_df['age_months'].median():.2f} months")

print(f"\n✅ Child Dataset shape: {child_df.shape}")
print(f"✅ New columns: {child_df.columns.tolist()}")

print("🧹 STEP 4: Removing Outliers\n")

def remove_outliers_iqr(df, columns, multiplier=1.5):
    """Remove outliers using IQR method"""
    df_clean = df.copy()
    initial_rows = len(df_clean)

    for col in columns:
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - multiplier * IQR
        upper_bound = Q3 + multiplier * IQR

        outliers = ((df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)).sum()
        if outliers > 0:
            print(f"  {col}: {outliers} outliers detected")
        df_clean = df_clean[(df_clean[col] >= lower_bound) & (df_clean[col] <= upper_bound)]

    removed = initial_rows - len(df_clean)
    return df_clean, removed

# CHILD DATASET
print("Child Dataset:")
child_df, removed = remove_outliers_iqr(child_df, ['ppvt'], multiplier=1.5)
print(f"  Removed: {removed} rows → New shape: {child_df.shape}")

# ADULT DATASET
print("\nAdult Dataset:")
adult_df, removed = remove_outliers_iqr(adult_df, ['Age', 'Memory_Test_Score', 'Cognitive_Score'])
print(f"  Removed: {removed} rows → New shape: {adult_df.shape}")

# OLD PEOPLE DATASET
print("\nOld People Dataset:")
old_df, removed = remove_outliers_iqr(old_df, ['Age', 'MMSE_Score', 'GDS_Score'])
print(f"  Removed: {removed} rows → New shape: {old_df.shape}")

print("\n✅ Outlier removal complete!")

print("📊 STEP 5: Normalizing Features\n")

def normalize_features(df, exclude_cols=None):
    """Normalize numeric columns to [0, 1] range"""
    if exclude_cols is None:
        exclude_cols = []

    df_copy = df.copy()
    scaler = MinMaxScaler()
    numeric_cols = df_copy.select_dtypes(include=['number']).columns
    numeric_cols = [col for col in numeric_cols if col not in exclude_cols]

    df_copy[numeric_cols] = scaler.fit_transform(df_copy[numeric_cols])
    return df_copy

# Normalize all datasets
child_df = normalize_features(child_df)
adult_df = normalize_features(adult_df, exclude_cols=['User_ID'])
old_df = normalize_features(old_df, exclude_cols=['Participant_ID'])

print("✅ Normalization complete!")
print(f"  All numeric features now in [0, 1] range")
print(f"\nChild stats: Mean={child_df['ppvt'].mean():.3f}, Std={child_df['ppvt'].std():.3f}")
print(f"Adult stats: Mean={adult_df['Cognitive_Score'].mean():.3f}, Std={adult_df['Cognitive_Score'].std():.3f}")
print(f"Old stats: Mean={old_df['MMSE_Score'].mean():.3f}, Std={old_df['MMSE_Score'].std():.3f}")

print("⚙️  STEP 6: Feature Engineering\n")

# CHILD DATASET
child_df['age_education_interaction'] = child_df['age_months'] * child_df['educ_cat']
print("✓ Child: Created age_education_interaction")

# ADULT DATASET
adult_df['stress_screentime_interaction'] = adult_df['Stress_Level'] * adult_df['Daily_Screen_Time']
print("✓ Adult: Created stress_screentime_interaction")

# OLD PEOPLE DATASET
old_df['cognitive_risk'] = old_df['Chronic_Diseases'] + old_df['GDS_Score']
print("✓ Old: Created cognitive_risk")

print("\n✅ Feature Engineering complete!")
print(f"Child columns: {child_df.shape[1]}")
print(f"Adult columns: {adult_df.shape[1]}")
print(f"Old columns: {old_df.shape[1]}")

print("📊 DATA SUMMARY AFTER CLEANING\n")

print("=" * 60)
print("CHILD DATASET")
print("=" * 60)
print(f"Shape: {child_df.shape}")
print(f"\nBasic Statistics:")
print(child_df.describe())
print(f"\nFirst 5 rows:")
print(child_df.head())

print("\n" + "=" * 60)
print("ADULT DATASET")
print("=" * 60)
print(f"Shape: {adult_df.shape}")
print(f"\nBasic Statistics:")
print(adult_df.describe())

print("\n" + "=" * 60)
print("OLD PEOPLE DATASET")
print("=" * 60)
print(f"Shape: {old_df.shape}")
print(f"\nBasic Statistics:")
print(old_df.describe())

# CHILD DATASET - PPVT Distribution
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# PPVT Distribution
axes[0, 0].hist(child_df['ppvt'], bins=30, color='skyblue', edgecolor='black')
axes[0, 0].set_title('Child PPVT (IQ Score) Distribution', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('PPVT Score (Normalized)')
axes[0, 0].set_ylabel('Frequency')

# Age Distribution
axes[0, 1].hist(child_df['age_months'], bins=20, color='lightcoral', edgecolor='black')
axes[0, 1].set_title('Child Age Distribution (Months)', fontsize=12, fontweight='bold')
axes[0, 1].set_xlabel('Age (Months)')
axes[0, 1].set_ylabel('Frequency')

# PPVT vs Age
axes[1, 0].scatter(child_df['age_months'], child_df['ppvt'], alpha=0.6, color='green')
axes[1, 0].set_title('PPVT vs Age', fontsize=12, fontweight='bold')
axes[1, 0].set_xlabel('Age (Months)')
axes[1, 0].set_ylabel('PPVT Score')

# Education Distribution
axes[1, 1].bar(child_df['educ_cat'].value_counts().index,
               child_df['educ_cat'].value_counts().values, color='orange')
axes[1, 1].set_title('Education Category Distribution', fontsize=12, fontweight='bold')
axes[1, 1].set_xlabel('Education Level')
axes[1, 1].set_ylabel('Count')

plt.tight_layout()
plt.show()

print("✅ Child Dataset visualizations complete!")

# ADULT DATASET VISUALIZATION
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Cognitive Score Distribution
axes[0, 0].hist(adult_df['Cognitive_Score'], bins=30, color='skyblue', edgecolor='black')
axes[0, 0].set_title('Cognitive Score Distribution', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('Cognitive Score')
axes[0, 0].set_ylabel('Frequency')

# Age Distribution
axes[0, 1].hist(adult_df['Age'], bins=20, color='lightcoral', edgecolor='black')
axes[0, 1].set_title('Adult Age Distribution', fontsize=12, fontweight='bold')
axes[0, 1].set_xlabel('Age')
axes[0, 1].set_ylabel('Frequency')

# Memory vs Cognitive Score
axes[1, 0].scatter(adult_df['Memory_Test_Score'], adult_df['Cognitive_Score'], alpha=0.5, color='green')
axes[1, 0].set_title('Memory vs Cognitive Score', fontsize=12, fontweight='bold')
axes[1, 0].set_xlabel('Memory Test Score')
axes[1, 0].set_ylabel('Cognitive Score')

# Stress Level Distribution
axes[1, 1].hist(adult_df['Stress_Level'], bins=20, color='orange', edgecolor='black')
axes[1, 1].set_title('Stress Level Distribution', fontsize=12, fontweight='bold')
axes[1, 1].set_xlabel('Stress Level')
axes[1, 1].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

print("✅ Adult Dataset visualizations complete!")

# OLD PEOPLE DATASET VISUALIZATION
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# MMSE Score Distribution
axes[0, 0].hist(old_df['MMSE_Score'], bins=30, color='skyblue', edgecolor='black')
axes[0, 0].set_title('MMSE Score Distribution', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('MMSE Score')
axes[0, 0].set_ylabel('Frequency')

# Age Distribution
axes[0, 1].hist(old_df['Age'], bins=20, color='lightcoral', edgecolor='black')
axes[0, 1].set_title('Old Age Distribution', fontsize=12, fontweight='bold')
axes[0, 1].set_xlabel('Age')
axes[0, 1].set_ylabel('Frequency')

# MMSE vs Age
axes[1, 0].scatter(old_df['Age'], old_df['MMSE_Score'], alpha=0.5, color='green')
axes[1, 0].set_title('MMSE vs Age', fontsize=12, fontweight='bold')
axes[1, 0].set_xlabel('Age')
axes[1, 0].set_ylabel('MMSE Score')

# Cognitive Impairment Count
axes[1, 1].bar(old_df['Cognitive_Impairment_Status'].value_counts().index,
               old_df['Cognitive_Impairment_Status'].value_counts().values,
               color='orange')
axes[1, 1].set_title('Cognitive Impairment Distribution', fontsize=12, fontweight='bold')
axes[1, 1].set_xlabel('Impairment (0 = No, 1 = Yes)')
axes[1, 1].set_ylabel('Count')

plt.tight_layout()
plt.show()

print("✅ Old Dataset visualizations complete!")

# CORRELATION MATRIX - ADULT DATASET
# Select only numeric columns
numeric_adult = adult_df.select_dtypes(include=[np.number])

# Create correlation matrix
correlation_matrix = numeric_adult.corr()

# Plot heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=False, cmap='coolwarm', center=0,
            square=True, linewidths=1)
plt.title('Adult Dataset - Feature Correlations', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Show top correlations with target variable (Cognitive_Score)
print("Top 10 Features Correlated with Cognitive_Score:")
correlations = correlation_matrix['Cognitive_Score'].sort_values(ascending=False)
print(correlations.head(11))  # 11 because first is itself

child_df.to_csv("child_cleaned_data.csv", index=False)

adult_df.to_csv("adult_cleaned_data.csv", index=False)

old_df.to_csv("old_cleaned_data.csv", index=False)

from google.colab import files

files.download("child_cleaned_data.csv")
files.download("adult_cleaned_data.csv")
files.download("old_cleaned_data.csv")

